image: registry.cdqidian.net/nodejs-docker:12.16.1
services:
  - registry.cdqidian.net/docker:18.06.0-ce-dind

before_script: 
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWD $DOCKER_REGISTRY

stages:
    - build

build_devel: 
    stage: build
    tags:
        - k8s
    retry:
        max: 2
        when: runner_system_failure
    script: 
        - echo "bulid devel test dokcer image."
        - npm install -g cnpm --registry=https://registry.npm.taobao.org
        - cnpm install 
        - cnpm run build:dev
        - docker build -t $DOCKER_REGISTRY/devel/cloudop:latest-dev .
        - docker push $DOCKER_REGISTRY/devel/cloudop:latest-dev
    only:
        refs: 
          - dev

build_test: 
    stage: build
    tags:
        - k8s
    script: 
        - echo "bulid beta test dokcer image."
        - npm install -g cnpm --registry=https://registry.npm.taobao.org
        - cnpm install 
        - cnpm run build:dev
        - docker build -t $DOCKER_REGISTRY/test/cloudop:$CI_COMMIT_TAG .
        - docker push $DOCKER_REGISTRY/test/cloudop:$CI_COMMIT_TAG
    only:
        refs: 
          - /^v\d+\.\d+\.\d+\-beta$/


build_prod:
    stage: build
    tags:
        - k8s
    retry:
        max: 2
        when: runner_system_failure
    script:
        - echo "build prod docker image."
        - npm install -g cnpm --registry=https://registry.npm.taobao.org
        - cnpm install 
        - cnpm run build:pre
        - docker build -t $DOCKER_REGISTRY/prod/cloudop .
        - docker push $DOCKER_REGISTRY/prod/cloudop:latest     
        - docker tag $DOCKER_REGISTRY/prod/cloudop:latest  $DOCKER_REGISTRY/prod/cloudop:$CI_COMMIT_TAG
        - docker push $DOCKER_REGISTRY/prod/cloudop:$CI_COMMIT_TAG
    only:
        refs:
          - /^v\d+\.\d+\.\d+$/


variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""